# Generated by Django 4.2.5 on 2023-09-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book_Donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_class_level",
                    models.CharField(
                        choices=[
                            ("KG", "Kindagarten"),
                            ("NUR", "Nursery"),
                            ("PRY", "Primary"),
                            ("JSS", "Junior Secondary School"),
                            ("SSS", "Senior Secondary School"),
                            ("UNI", "University"),
                        ],
                        db_index=True,
                        default="KG",
                        max_length=3,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("book_amount", models.IntegerField()),
                ("phone_number", models.CharField(max_length=11)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Book_Receiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_class_level",
                    models.CharField(
                        choices=[
                            ("KG", "Kindagarten"),
                            ("NUR", "Nursery"),
                            ("PRY", "Primary"),
                            ("JSS", "Junior Secondary School"),
                            ("SSS", "Senior Secondary School"),
                            ("UNI", "University"),
                        ],
                        db_index=True,
                        default="KG",
                        max_length=3,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("book_amount", models.IntegerField()),
                ("phone_number", models.CharField(max_length=11)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
