# Generated by Django 4.2.5 on 2023-10-08 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("BookDonations", "0002_book_receiver_drop_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book_donor",
            name="drop_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
